#!/bin/bash

# ===================================================================================================
# SCRIPT: recover_t1ss.sh
# METHOD: Hatano Skull Stripping Method - T1 Sqr Strip Recovery (v2.11)
# STRATEGY: Restore original PreFS/HCP outputs modified by t1sqr-strip
# GITHUB: https://github.com/koji-hatano1/t1sqr-strip
# ===================================================================================================

# --- Configuration ---
Subjlist="001 002 003"
BASE_PATH="/path/to/your/project"

# --- Global logging ---
TIMESTAMP=$(date '+%Y%m%d_%H%M%S')
LOG_FILE="recover_t1ss_v2.11_${TIMESTAMP}.log"

log_info() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] [INFO] $1" | tee -a "$LOG_FILE"
}

log_warn() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] [WARN] $1" | tee -a "$LOG_FILE"
}

log_info "=== t1sqr-strip Recovery v2.11 Started ==="

for SESSION in ${Subjlist}; do
    log_info "-----------------------------------------------------------"
    log_info "Starting Recovery Session: ${SESSION}"

    T1wFolder="${BASE_PATH}/${SESSION}/T1w"
    AtlasSpaceFolder="${BASE_PATH}/${SESSION}/MNINonLinear"

    if [ ! -d "$T1wFolder" ]; then
        log_warn "T1w folder not found: $T1wFolder"
    fi

    if [ ! -d "$AtlasSpaceFolder" ]; then
        log_warn "MNINonLinear folder not found: $AtlasSpaceFolder"
    fi

    # --- 1. Restore T1w-space files from _bet backups ---
    if [ -d "$T1wFolder" ]; then
        log_info "Restoring T1w-space files..."

        for backup in "${T1wFolder}"/*_bet.nii.gz; do
            if [ -f "$backup" ]; then
                original="${backup%_bet.nii.gz}.nii.gz"
                log_info "Restoring: $(basename "$original")"
                rm -f "$original"
                mv -f "$backup" "$original"
            fi
        done
    fi

    # --- 2. Restore MNINonLinear files from _bet backups ---
    if [ -d "$AtlasSpaceFolder" ]; then
        log_info "Restoring MNINonLinear files..."

        for backup in "${AtlasSpaceFolder}"/*_bet.nii.gz; do
            if [ -f "$backup" ]; then
                original="${backup%_bet.nii.gz}.nii.gz"
                log_info "Restoring: $(basename "$original")"
                rm -f "$original"
                mv -f "$backup" "$original"
            fi
        done
    fi

    # --- 3. Remove temporary files generated by t1sqr-strip ---
    log_info "Cleaning temporary files..."

    rm -f "${T1wFolder}/T1w_tmp_brain.nii.gz"
    rm -f "${T1wFolder}/T1w_tmp_mask.nii.gz"
    rm -f "${T1wFolder}/T1w_sqr_tmp.nii.gz"
    rm -f "${T1wFolder}/T1w_tmp_thr_mask.nii.gz"
    rm -f "${AtlasSpaceFolder}/tmp_m.nii.gz"
    rm -f "${AtlasSpaceFolder}/tmp_t1ss_m.nii.gz"
    rm -f "${AtlasSpaceFolder}/tmp_t1sqr_m.nii.gz"

    log_info "Finished Recovery Session: ${SESSION}"
done

log_info "-----------------------------------------------------------"
log_info "t1sqr-strip Recovery v2.11 Complete."
log_info "-----------------------------------------------------------"